[package]
name = "gauth"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenv = "0.15.0"
serde = "1.0.217"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls", "runtime-tokio", "time", "chrono"] }

[lib]
name="gauth"
path="src/lib.rs"